highlighter: pygments
markdown: kramdown
google_analytics:
show_downloads: true
plugins:
  - jekyll-redirect-from

kramdown:
  entity_output: numeric

include:
  - _static
  - _modules

MOONBOX_VERSION: 0.3.0-beta
MOONBOX_VERSION_SHORT: 0.3.0
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.8"
